### ISSUE TITLE
IllegalAccessError with Gradle 3.0 in VersionConfiguringAction.isDependencyOnLocalProject

### ISSUE THREAD

**Issue by wilkinsona** [spring-gradle-plugins/dependency-management-plugin#112]
```
Caused by: java.lang.IllegalAccessError: io/spring/gradle/dependencymanagement/VersionConfiguringAction$_isDependencyOnLocalProject_closure1
        at io.spring.gradle.dependencymanagement.VersionConfiguringAction.isDependencyOnLocalProject(VersionConfiguringAction.groovy:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:214)
        at io.spring.gradle.dependencymanagement.VersionConfiguringAction.execute(VersionConfiguringAction.groovy:52)
        at io.spring.gradle.dependencymanagement.VersionConfiguringAction.execute(VersionConfiguringAction.groovy)
        at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DefaultDependencySubstitutions$DependencyResolveDetailsWrapperAction.execute(DefaultDependencySubstitutions.java:195)
        at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DefaultDependencySubstitutions$DependencyResolveDetailsWrapperAction.execute(DefaultDependencySubstitutions.java:185)
        at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:79)
        at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:79)
        at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:79)
        at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DependencySubstitutionResolver.resolve(DependencySubstitutionResolver.java:40)
        ... 69 more
```

I think this is a Groovy problem as there's no reason why `isDependencyOnLocalProject` shouldn't be able to access a closure declared in the same method. It may be caused by the plugin being compiled with Gradle 1.12 (Groovy 1.8) and running with Gradle 3.0 (Groovy 2.4).

@lhotari I'd welcome your expert input here if you have the time. Does my somewhat educated guess above sound likely to you?

It may be possible to work around this problem by rewriting `VersionConfiguringAction` in Java. I've been slowly converting the bulk of the plugin from Groovy to Java anyway.

**Comment by wilkinsona** [comment]
Sample from @yidongnan that reproduces the failure: https://github.com/yidongnan/dependency-management-plugin-error-in-gradle-3.0

**Comment by lhotari** [comment]
@wilkinsona Yes, It's probably related to the plugin being compiled with Groovy 1.8. and executed with Groovy 2.4 . 

The method `isDependencyOnLocalProject` is a `private static` method. There are big differences in the bytecode that Groovy 1.8 produces compared to Groovy 2.4 . The relevant difference in this case might be that the closure class is public in Groovy 2.4. I used `javap './build/classes/main/io/spring/gradle/dependencymanagement/VersionConfiguringAction$_isDependencyOnLocalProject_closure1.class'` command to find out that difference. I tested the output of Gradle 2.7 which is using Groovy 2.3.10. The closure class doesn't have the public modifier in 2.3.x either so this has changed in Groovy 2.4.x .

I assume that the Groovy 2.4 runtime expects that the closure class is public. I searched the Groovy Jira for bug reports, but didn't find one that matches this problem. @melix , do you know what could be causing this particular problem? Should Groovy 2.4.x support code compiled with Groovy 1.8.x ?

I've faced similar IllegalAccessError problems with Groovy in the past and the usual workaround is to change the method access modifiers. In this case, the workaround might be removing the `static` modifier from the `isDependencyOnLocalProject` method.

@yidongnan I tried to reproduce the problem with the project https://github.com/yidongnan/dependency-management-plugin-error-in-gradle-3.0  , but I didn't get any errors running `dependencyManagement`, `assemble`,  `:core:dependencies` or `:alpha:dependencies` tasks. The project had Gradle wrapper for `2.11` and I also tested with `3.0` . How can I reproduce the problem?

**Comment by yidongnan** [comment]
@lhotari change gradle to 3.0 
https://github.com/yidongnan/dependency-management-plugin-error-in-gradle-3.0/blob/master/gradle/wrapper/gradle-wrapper.properties#L7
https://github.com/yidongnan/dependency-management-plugin-error-in-gradle-3.0/blob/master/build.gradle#L12
```gradlew.bat :core:clean :core:build ``` can reproduce the problem

**Comment by wilkinsona** [comment]
Thanks very much, @lhotari.

@melix @lhotari I'm trying to support Gradle 1, 2, and 3 with the same binary. Is that overly ambitious? I'm currently building the plugin with Gradle 1.12. I also build and test with 2.x and 3.0. What this issue shows is that I'm missing some tests that build with Gradle 1.12 and test with Gradle 2.x and 3.0.

**Comment by melix** [comment]
I am unsure what could cause this, but I agree that compiling with 1.8 and running with 2.4 is likely to cause problems. Doing this is very ambitious, yes :) Given that the Groovy runtime in Gradle 1, 2 and 3 are very different, if you want to do this, I would rather suggest to use "good" old Java. Alternatively, you might want to try using `@CompileStatic` with a version of Gradle that comes with Groovy 2 minimally. It would be less sensible to changes, but nevertheless could have binary incompatibilities.

**Comment by lhotari** [comment]
Thanks @yidongnan , now I can reproduce the problem.

**Comment by lhotari** [comment]
@melix Now that I was able to reproduce the problem. It makes me wonder why this passes with Gradle 2.14.1 , but fails with Gradle 3.0 . Gradle 2.14.1 has Groovy 2.4.4 and Gradle 3.0 has Groovy 2.4.7 .
I started thinking if this could be a problem caused by some of the bytecode instrumentations that Gradle does on the fly for plugin classes.

**Comment by melix** [comment]
That could be a good reason too. If the bytecode instrumentation changes the access flags...

**Comment by lhotari** [comment]
I tested with a [custom build of Gradle](https://github.com/lhotari/gradle/commits/lh-2.14.1-with-Groovy-2.4.7) which is REL_2.14.1 + commits to upgrade to use Groovy 2.4.7 .  That passes so it rules out the Groovy version. It's likely that the Gradle on-the-fly bytecode instrumentation that happens at runtime might be involved in causing the problem to manifest.

**Comment by lhotari** [comment]
I did this simple change and that made the problem go away: https://github.com/lhotari/dependency-management-plugin-error-in-gradle-3.0/commit/9e45d994 . I'm not sure what's going on. It could be classloader related as well.

**Comment by lhotari** [comment]
This is another way I can make the test build to pass with Gradle 3.0 https://github.com/yidongnan/dependency-management-plugin-error-in-gradle-3.0/commit/634b4b87

**Comment by lhotari** [comment]
There seems to be several problems around this.

[with my lh-snapshot-version branch of the test project](https://github.com/lhotari/dependency-management-plugin-error-in-gradle-3.0/tree/lh-snapshot-version) I can use `0.6.1.BUILD-SNAPSHOT` version of the locally compiled dependency-management-plugin. When I compile the master branch of dependency-management-plugin with Gradle 3.0 or my [custom version of Gradle 2.14.1 with Groovy 2.4.7](https://github.com/lhotari/gradle/commits/lh-2.14.1-with-Groovy-2.4.7), I get this error in the test project:

```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "io.spring.gradle.dependencymanagement.org.apache.maven.model.building.DefaultModelBuildingRequest.setModelSource(Lio/spring/gradle/dependencymanagement/org/apache/maven/model/building/ModelSource;)Lio/spring/gradle/dependencymanagement/org/apache/maven/model/building/DefaultModelBuildingRequest;" the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) of the current class, io/spring/gradle/dependencymanagement/maven/EffectiveModelBuilder, and the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) for the method's defining class, io/spring/gradle/dependencymanagement/org/apache/maven/model/building/DefaultModelBuildingRequest, have different Class objects for the type io/spring/gradle/dependencymanagement/org/apache/maven/model/building/ModelSource used in the signature
        at io.spring.gradle.dependencymanagement.maven.EffectiveModelBuilder.buildModel(EffectiveModelBuilder.java:49)
        at io.spring.gradle.dependencymanagement.maven.EffectiveModelBuilder$buildModel.call(Unknown Source)
        at io.spring.gradle.dependencymanagement.DependencyManagement$_resolve_closure4.doCall(DependencyManagement.groovy:173)
        at io.spring.gradle.dependencymanagement.DependencyManagement.resolve(DependencyManagement.groovy:170)
        at io.spring.gradle.dependencymanagement.DependencyManagement.resolveIfNecessary(DependencyManagement.groovy:136)
        at io.spring.gradle.dependencymanagement.DependencyManagement.getManagedVersion(DependencyManagement.groovy:107)
        at io.spring.gradle.dependencymanagement.DependencyManagement$getManagedVersion$0.call(Unknown Source)
        at io.spring.gradle.dependencymanagement.DependencyManagementContainer.getManagedVersion(DependencyManagementContainer.groovy:85)
        at io.spring.gradle.dependencymanagement.DependencyManagementContainer$getManagedVersion$0.call(Unknown Source)
        at io.spring.gradle.dependencymanagement.VersionConfiguringAction.execute(VersionConfiguringAction.groovy:62)
        at io.spring.gradle.dependencymanagement.VersionConfiguringAction.execute(VersionConfiguringAction.groovy)
        at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DefaultDependencySubstitutions$DependencyResolveDetailsWrapperAction.execute(DefaultDependencySubstitutions.java:195)
        at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DefaultDependencySubstitutions$DependencyResolveDetailsWrapperAction.execute(DefaultDependencySubstitutions.java:185)
        at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:79)
        at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:79)
        at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:79)
        at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DependencySubstitutionResolver.resolve(DependencySubstitutionResolver.java:40)
        ... 66 more
```

However if I compile the plugin with Gradle 2.14.1 (Groovy 2.4.4), I get the original exception (IllegalAccessException). 

There seems to be several problems here. This LinkageError exception is also classloader related.

**Comment by lhotari** [comment]
The previous LinkageError problem doesn't occur with Gradle compiled from release branch so that one is fixed. I'm sorry for the noise.

**Comment by wilkinsona** [comment]
I'm going to stop trying to support Gradle 3.0, for the time being at least. #114 is the straw that broke the camel's back.
