### ISSUE TITLE
overriding version property with a bom

### ISSUE THREAD

**Issue by ezraroi** [spring-gradle-plugins/dependency-management-plugin#208]
Hi,
i have a bom that i generate using this plugin and the bom the i generate includes spring boot and spring cloud boms.

I am trying to override some of the versions with my bom, but any of the methods specified here are not working when i am trying to use them in the bom i generate.

The only way to override the verison is in the gradle.properties of the application using my bom.
This is not good enough as  we have 20+ such services and we want to override the version in one place (our bom).

Is there a way to achieve this?

**Comment by wilkinsona** [comment]
> Is there a way to achieve this?

Yes. Perhaps you can share what you’ve tried? Also, please note that a bug’s been fixed in this area in 1.0.5 snapshots (#204).

**Comment by ezraroi** [comment]
This is my pom:
```
<?xml version="1.0" encoding="UTF-8"?>                                                                        
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">                                                                                                                                                                          
  <modelVersion>4.0.0</modelVersion>                                                                                                                                                       
  <groupId>com.intel.swiss.microservices.framework</groupId>                                                                                                                               
  <artifactId>swiss-spring-dependencies</artifactId>                                                                                                                                       
  <version>1.1.6-SNAPSHOT</version>                                                                                                                                                        
  <packaging>pom</packaging>                                                                                                                                                               
  <dependencyManagement>                                                                                                                                                                   
    <dependencies>                                                                                                                                                                         
      <dependency>                                                                                                                                                                         
        <groupId>org.springframework.cloud</groupId>                                                                                                                                       
        <artifactId>spring-cloud-dependencies</artifactId>                                                                                                                                 
        <version>Edgware.SR2</version>                                                                                                                                                     
        <scope>import</scope>                                                                                                                                                              
        <type>pom</type>                                                                                                                                                                   
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>org.springframework.boot</groupId>                                                                                                                                        
        <artifactId>spring-boot-starter-parent</artifactId>                                                                                                                                
        <version>1.5.10.RELEASE</version>                                                                                                                                                  
        <scope>import</scope>                                                                                                                                                              
        <type>pom</type>                                                                                                                                                                   
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>io.springfox</groupId>                                                                                                                                                    
        <artifactId>springfox-swagger-ui</artifactId>                                                                                                                                      
        <version>2.8.0</version>                                                                                                                                                           
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.fasterxml.jackson.datatype</groupId>                                                                                                                                  
        <artifactId>jackson-datatype-jsr310</artifactId>                                                                                                                                   
        <version>2.8.10</version>                                                                                                                                                          
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>org.flywaydb</groupId>                                                                                                                                                    
        <artifactId>flyway-core</artifactId>                                                                                                                                               
        <version>4.2.0</version>                                                                                                                                                           
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.fasterxml.jackson.datatype</groupId>                                                                                                                                  
        <artifactId>jackson-datatype-json-org</artifactId>                                                                                                                                 
        <version>2.8.10</version>                                                                                                                                                          
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>io.springfox</groupId>                                                                                                                                                    
        <artifactId>springfox-swagger2</artifactId>                                                                                                                                        
        <version>2.8.0</version>                                                                                                                                                           
        <exclusions>                                                                                                                                                                       
          <exclusion>                                                                                                                                                                      
            <groupId>org.mapstruct</groupId>                                                                                                                                               
            <artifactId>mapstruct</artifactId>                                                                                                                                             
          </exclusion>                                                                                                                                                                     
        </exclusions>                                                                                                                                                                      
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.intel.swiss.microservices.framework</groupId>                                                                                                                         
        <artifactId>swiss-spring-security-common</artifactId>                                                                                                                              
        <version>1.1.6-SNAPSHOT</version>                                                                                                                                                  
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.intel.swiss.microservices.framework</groupId>                                                                                                                         
        <artifactId>swiss-spring-security</artifactId>                                                                                                                                     
        <version>1.1.6-SNAPSHOT</version>                                                                                                                                                  
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>org.mapstruct</groupId>                                                                                                                                                   
        <artifactId>mapstruct-processor</artifactId>                                                                                                                                       
        <version>1.2.0.Final</version>                                                                                                                                                     
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.intel.swiss.microservices.framework</groupId>                                                                                                                         
        <artifactId>swiss-spring-data</artifactId>                                                                                                                                         
        <version>1.1.6-SNAPSHOT</version>                                                                                                                                                  
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.intel.swiss.microservices.framework</groupId>                                                                                                                         
        <artifactId>swiss-spring-test</artifactId>                                                                                                                                         
        <version>1.1.6-SNAPSHOT</version>                                                                                                                                                  
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.intel.swiss.microservices.framework</groupId>                                                                                                                         
        <artifactId>swiss-spring-webapp</artifactId>                                                                                                                                       
        <version>1.1.6-SNAPSHOT</version>                                                                                                                                                  
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.zaxxer</groupId>                                                                                                                                                      
        <artifactId>HikariCP</artifactId>                                                                                                                                                  
        <version>2.7.8</version>                                                                                                                                                           
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.intel.swiss.microservices.framework</groupId>                                                                                                                         
        <artifactId>swiss-spring-api-gateway</artifactId>                                                                                                                                  
        <version>1.1.6-SNAPSHOT</version>                                                                                                                                                  
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.fasterxml.jackson.datatype</groupId>                                                                                                                                  
        <artifactId>jackson-datatype-hppc</artifactId>                                                                                                                                     
        <version>2.8.10</version>                                                                                                                                                          
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>org.projectlombok</groupId>                                                                                                                                               
        <artifactId>lombok</artifactId>                                                                                                                                                    
        <version>1.16.20</version>                                                                                                                                                         
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.intel.swiss.microservices.framework</groupId>                                                                                                                         
        <artifactId>swiss-spring-legacy</artifactId>                                                                                                                                       
        <version>1.1.6-SNAPSHOT</version>                                                                                                                                                  
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>io.dropwizard.metrics</groupId>                                                                                                                                           
        <artifactId>metrics-core</artifactId>                                                                                                                                              
        <version>3.1.5</version>                                                                                                                                                           
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>org.flywaydb.flyway-test-extensions</groupId>                                                                                                                             
        <artifactId>flyway-spring-test</artifactId>                                                                                                                                        
        <version>4.2.0.2</version>                                                                                                                                                         
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>javax.validation</groupId>                                                                                                                                                
        <artifactId>validation-api</artifactId>                                                                                                                                            
        <version>1.1.0.Final</version>                                                                                                                                                     
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.intel.swiss.microservices.framework</groupId>                                                                                                                         
        <artifactId>swiss-spring-common</artifactId>                                                                                                                                       
        <version>1.1.6-SNAPSHOT</version>                                                                                                                                                  
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.intel.swiss.microservices.framework</groupId>                                                                                                                         
        <artifactId>swiss-spring-cloud</artifactId>                                                                                                                                        
        <version>1.1.6-SNAPSHOT</version>                                                                                                                                                  
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>io.springfox</groupId>                                                                                                                                                    
        <artifactId>springfox-bean-validators</artifactId>                                                                                                                                 
        <version>2.8.0</version>                                                                                                                                                           
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>io.dropwizard.metrics</groupId>                                                                                                                                           
        <artifactId>metrics-annotation</artifactId>                                                                                                                                        
        <version>3.1.5</version>                                                                                                                                                           
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>com.fasterxml.jackson.datatype</groupId>                                                                                                                                  
        <artifactId>jackson-datatype-hibernate5</artifactId>                                                                                                                               
        <version>2.8.10</version>                                                                                                                                                          
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>org.mapstruct</groupId>                                                                                                                                                   
        <artifactId>mapstruct-jdk8</artifactId>                                                                                                                                            
        <version>1.2.0.Final</version>                                                                                                                                                     
      </dependency>                                                                                                                                                                        
      <dependency>                                                                                                                                                                         
        <groupId>io.dropwizard.metrics</groupId>
        <artifactId>metrics-jvm</artifactId>
        <version>3.1.5</version>
      </dependency>
      <dependency>
        <groupId>io.dropwizard.metrics</groupId>
        <artifactId>metrics-json</artifactId>
        <version>3.1.5</version>
      </dependency>
      <dependency>
        <groupId>io.swagger</groupId>
        <artifactId>swagger-annotations</artifactId>
        <version>1.5.13</version>
      </dependency>
      <dependency>
        <groupId>com.intel.swiss.microservices.framework</groupId>
        <artifactId>swiss-spring-sample</artifactId>
        <version>1.1.6-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.datatype</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>2.8.10</version>
      </dependency>
      <dependency>
        <groupId>com.intel.swiss.microservices.framework</groupId>
        <artifactId>swiss-spring-security-kerb</artifactId>
        <version>1.1.6-SNAPSHOT</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <properties>
    <hikaricp.version>2.7.8</hikaricp.version>
    <flyway.version>4.2.0</flyway.version>
  </properties>
</project>
```

**Comment by ezraroi** [comment]
i have added to my pom the following properties and I import this bom in my application.

This is what i get:
![image](https://user-images.githubusercontent.com/5808368/37258371-9e8f8e8c-257f-11e8-99c1-7aca731328c5.png)

**Comment by wilkinsona** [comment]
Maven doesn’t support using properties to override versions in an imported bom. That’s nothing to do with this plugin; it’s just the way that Maven works. If you want a Maven bom to override dependency management in a bom that it imports you need to explicitly declare the dependency management before importing that is to be overridden.

**Comment by ezraroi** [comment]
So it is not possible to achive it through my bom that includes spring boms?

**Comment by ezraroi** [comment]
also, the dependency-management-plugin allows us to override the version of dependencies with properties in our gradle project and it is using the properties from boot pm for example, this is why we decided to try add properties to the bom.

**Comment by wilkinsona** [comment]
> So it is not possible to achive it through my bom that includes spring boms? Or the order of nodes in my pom can control this? I generate my pom using the groovy dsl

Yes, it's possible. But you need to declare the overriding dependency management before importing the bom that you're overriding:

```xml
<?xml version="1.0" encoding="UTF-8"?>                                                                        
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">                                                                                                                                                                          
  <modelVersion>4.0.0</modelVersion>                                                                                                                                                       
  <groupId>com.intel.swiss.microservices.framework</groupId>                                                                                                                               
  <artifactId>swiss-spring-dependencies</artifactId>                                                                                                                                       
  <version>1.1.6-SNAPSHOT</version>                                                                                                                                                        
  <packaging>pom</packaging>                                                                                                                                                               
  <dependencyManagement>           
    <dependencies>
      <dependency>                                                                                                                                                                         
        <groupId>com.zaxxer</groupId>                                                                                                                                                      
        <artifactId>HikariCP</artifactId>                                                                                                                                                  
        <version>2.7.8</version>                                                                                                                                                           
      </dependency>
      <dependency>                                                                                                                                                                         
        <groupId>org.springframework.boot</groupId>                                                                                                                                        
        <artifactId>spring-boot-starter-parent</artifactId>                                                                                                                                
        <version>1.5.10.RELEASE</version>                                                                                                                                                  
        <scope>import</scope>                                                                                                                                                              
        <type>pom</type>                                                                                                                                                                   
      </dependency> 
    </dependencies>
  </dependencyManagement>
</project>                       
```

> also, the dependency-management-plugin allows us to override the version of dependencies with properties in our gradle project and it is using the properties from boot pm for example, this is why we decided to try add properties to the bom.

Your bom's not actually using the properties:

```xml
      <dependency>                                                                                                                                                                         
        <groupId>com.zaxxer</groupId>                                                                                                                                                      
        <artifactId>HikariCP</artifactId>                                                                                                                                                  
        <version>2.7.8</version>                                                                                                                                                           
      </dependency>
```

```
  <properties>
    <hikaricp.version>2.7.8</hikaricp.version>
    <flyway.version>4.2.0</flyway.version>
  </properties>
```

The version of the dependency needs to be `${hikaricp.version}`.

In looking at this, it's become apparent that the problem's you're facing don't appear to have anything to do with this plugin so I'm going to close this issue. Unfortunately, I don't have time to provide general help with creating a Maven bom.

**Comment by ezraroi** [comment]
thanks

**Comment by bjmi** [comment]
But all transitive dependencies are not overridden i.e. may have wrong versions and cause interoperability problems.
Good example is overriding _org.junit.jupiter:junit-jupiter_ but all transitive versions differ and result in e.g. ClassNotFoundExceptions and so on.
```
org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
java.lang.NoClassDefFoundError: org/junit/platform/commons/util/LruCache
    at org.junit.vintage.engine.descriptor.TestSourceProvider.<init>(TestSourceProvider.java:38)
    at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:42)
    at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:63)
```

**Comment by wilkinsona** [comment]
@bjmi It's not clear to me how your comment relates to this two-year-old issue. If you override the version of a single module in a multi-module library than that will likely result in incompatibilities. That's true no matter how you're managing dependency versions in Maven or Gradle and isn't specific to this plugin.

**Comment by bjmi** [comment]
It just documents the drawbacks of following proposed solution, not more.
> Yes, it's possible. But you need to declare the overriding dependency management before importing the bom that you're overriding:

**Comment by wilkinsona** [comment]
Unless I have misunderstood, I don't think the proposed solution has that drawback. That problem will only occur if your overrides are incomplete and you haven't implemented the solution correctly. That's really got nothing to do with this plugin, though. It's all down to the way that Maven works.

**Comment by bjmi** [comment]
> That problem will only occur if your overrides are incomplete and you haven't implemented the solution correctly. 
If you have to override a complete dependency subtree (all transitive deps) then the solution has a negative connotation.

> That's really got nothing to do with this plugin, though. It's all down to the way that Maven works.
Right! :)
