### ISSUE TITLE
ArrayIndexOutOfBoundsException when generating POM if a dependency management exclude does not specify an artifact id

### ISSUE THREAD

**Issue by greenrd** [spring-gradle-plugins/dependency-management-plugin#214]
We got this exception

```
[18:08:40][Gradle failure report] Caused by: org.gradle.api.InvalidUserCodeException: Could not apply withXml() to generated POM
[18:08:40][Gradle failure report] 	at org.gradle.api.internal.UserCodeAction.execute(UserCodeAction.java:40)
[18:08:40][Gradle failure report] 	at org.gradle.internal.ImmutableActionSet$CompositeSet.execute(ImmutableActionSet.java:196)
[18:08:40][Gradle failure report] 	at org.gradle.internal.MutableActionSet.execute(MutableActionSet.java:35)
[18:08:40][Gradle failure report] 	at org.gradle.internal.xml.XmlTransformer$XmlProviderImpl.apply(XmlTransformer.java:174)
[18:08:40][Gradle failure report] 	at org.gradle.internal.xml.XmlTransformer.doTransform(XmlTransformer.java:146)
[18:08:40][Gradle failure report] 	at org.gradle.internal.xml.XmlTransformer.doTransform(XmlTransformer.java:134)
[18:08:40][Gradle failure report] 	at org.gradle.internal.xml.XmlTransformer.transform(XmlTransformer.java:98)
[18:08:40][Gradle failure report] 	at org.gradle.internal.xml.XmlTransformer$1.execute(XmlTransformer.java:76)
[18:08:40][Gradle failure report] 	at org.gradle.internal.xml.XmlTransformer$1.execute(XmlTransformer.java:74)
[18:08:40][Gradle failure report] 	at org.gradle.internal.IoActions$TextFileWriterIoAction.execute(IoActions.java:145)
[18:08:40][Gradle failure report] 	... 110 more
[18:08:40][Gradle failure report] Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
[18:08:40][Gradle failure report] 	at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.addManagedDependency(StandardPomDependencyManagementConfigurer.java:218)
[18:08:40][Gradle failure report] 	at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.configureManagedDependencies(StandardPomDependencyManagementConfigurer.java:200)
[18:08:40][Gradle failure report] 	at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.doConfigurePom(StandardPomDependencyManagementConfigurer.java:116)
[18:08:40][Gradle failure report] 	at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.configurePom(StandardPomDependencyManagementConfigurer.java:102)
[18:08:40][Gradle failure report] 	at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.execute(StandardPomDependencyManagementConfigurer.java:96)
[18:08:40][Gradle failure report] 	at io.spring.gradle.dependencymanagement.internal.StandardPomDependencyManagementConfigurer.execute(StandardPomDependencyManagementConfigurer.java:44)
[18:08:40][Gradle failure report] 	at org.gradle.api.internal.UserCodeAction.execute(UserCodeAction.java:38)
[18:08:40][Gradle failure report] 	... 119 more

```

The workaround was to change this line in our gradle file:

```            exclude "com.eclipsesource.j2v8"```

to this:

```            exclude "com.eclipsesource.j2v8:*"```

**Comment by greenrd** [comment]
Yes, exactly - we have something like that.

**Comment by wilkinsona** [comment]
Thanks. The exclude without an artifact id should be rejected up front rather than failing later. Note that your work around probably isn't working as you expect. There's no wildcard support in exclusions so, while, `com.eclipsesource.j2v8:*` does not fail, it also will not exclude any dependencies in the `com.eclipsesource.j2v8` group from your Gradle build's dependencies.
