### ISSUE TITLE
java.lang.StackOverflowError when using dep-mgnt  'org.apache.xmlgraphics:batik-rasterizer' '1.7'  and 'applyMavenExclusions==true'

### ISSUE THREAD

**Issue by fwalk** [spring-gradle-plugins/dependency-management-plugin#33]
Hi 
StackOverflowError  exception is thrown when using 'org.apache.xmlgraphics:batik-rasterizer' '1.7' with default of applyMavenExclusions. 

Sample code
```
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: "io.spring.dependency-management"

sourceCompatibility = 1.7
version = '1.0'

repositories { mavenCentral() }

buildscript {
	repositories { mavenCentral() }
	dependencies { classpath "io.spring.gradle:dependency-management-plugin:0.4.0.RELEASE" }
}

dependencyManagement {
	// applyMavenExclusions false
	dependencies { 'org.apache.xmlgraphics:batik-rasterizer' '1.7' }
}

dependencies { compile 'org.apache.xmlgraphics:batik-rasterizer' }

task createWrapper(type: Wrapper) { gradleVersion = '1.12' }

```

Stacktrace snipped: 
```
20:00:50.646 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.StackOverflowError
20:00:50.646 [ERROR] [org.gradle.BuildExceptionReporter]        at io.spring.gradle.dependencymanagement.exclusions.DependencyGraph.process(DependencyGraph.groovy:47)
20:00:50.646 [ERROR] [org.gradle.BuildExceptionReporter]        at io.spring.gradle.dependencymanagement.exclusions.DependencyGraph$_process_closure3.doCall(DependencyGraph.groovy:47)
```
regards, Frank

**Comment by wilkinsona** [comment]
There's a circular dependency between `org.apache.xmlgraphics:batik-svgdom` and `org.apache.xmlgraphics:batik-anim`. I'm surprised it's even possible to tag and release a project with circular dependencies between its modules, but apparently it is so the plugin needs to cope with it.

**Comment by fwalk** [comment]
cool, i can confirm that it's solved.
thx, Frank

**Comment by wilkinsona** [comment]
Thanks for trying a snapshot
