### ISSUE TITLE
Pom Generation

### ISSUE THREAD

**Issue by RobWin** [spring-gradle-plugins/dependency-management-plugin#37]
Hello its more a question than an issue I guess.
 
the Pom generation with an import of the spring io BOM fails behind a HTTP proxy, because Gradle is not able to retrieve the BOM.
It seems that the Maven Integration in Gradle has a bug. Neither Maven's HTTP proxy settings nor Gradle's seem to work.
Did you ever tried that and maybe you have a solution?

Kind regards Robert

**Comment by wilkinsona** [comment]
You can configure the plugin to copy any imported boms into the generated pom:

```
dependencyManagement {
    generatedPomCustomization {
        importedBomAction = 'copy'
    }
}
```

**Comment by RobWin** [comment]
I'll try that.thx

**Comment by RobWin** [comment]
Thx thx. It works like a charm. 
Finally a soltion :)

**Comment by RobWin** [comment]
Hi,

version 1.0.0 fails with the following exception now:

```
Caused by: groovy.lang.MissingPropertyException: No such property: importedBomAction for class: io.spring.gradle.dependencymanagement.internal.dsl.StandardGeneratedPomCustomizationHandler
        at build_bmkma4n0ivd01buux3s0t1sg5$_run_closure2$_closure7$_closure9.doCall(/Users/robwin/IdeaProjects/spica-messaging/build.gradle:91)
        at io.spring.gradle.dependencymanagement.internal.dsl.ClosureBackedAction.execute(ClosureBackedAction.java:44)
        at io.spring.gradle.dependencymanagement.internal.dsl.StandardDependencyManagementExtension.generatedPomCustomization(StandardDependencyManagementExtension.java:138)
        at io.spring.gradle.dependencymanagement.internal.dsl.StandardDependencyManagementExtension.generatedPomCustomization(StandardDependencyManagementExtension.java:133)
```

Is there an alternative to `importedBomAction = 'copy'`?

**Comment by wilkinsona** [comment]
It was removed in 1.0.0.RC1 as the limitation in Gradle that required the copy has been fixed. See #131.

**Comment by RobWin** [comment]
Thx for the quick response 👍
