### ISSUE TITLE
Error using local M2 repo

### ISSUE THREAD

**Issue by kpb** [spring-gradle-plugins/dependency-management-plugin#81]
I'm developing in a restricted environment without internet access. To 'work around' this (hell), I created a M2 repository with all the files required, including the dependency-management-plugin. This sample is created using `$ spring init --build=gradle -j=1.8 -d=cloud-eureka-server foo`.

I changed the repositories to `mavenLocal()`, but I get an error:

```bash
$ gradle --stacktrace build
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Cannot change dependencies of configuration 'detachedConfiguration1' after it has been resolved.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.InvalidUserDataException: Cannot change dependencies of configuration 'detachedConfiguration1' after it has been resolved.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.validateMutation(DefaultConfiguration.java:600)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$2.run(DefaultConfiguration.java:149)
	at org.gradle.api.internal.DefaultDomainObjectCollection.assertMutable(DefaultDomainObjectCollection.java:267)
	at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:158)
	at org.gradle.api.internal.DelegatingDomainObjectSet.add(DelegatingDomainObjectSet.java:81)
	at java_util_Set$add$1.call(Unknown Source)
	at io.spring.gradle.dependencymanagement.DependencyManagement$_resolve_closure2.doCall(DependencyManagement.groovy:152)
	at io.spring.gradle.dependencymanagement.DependencyManagement.resolve(DependencyManagement.groovy:152)
	at io.spring.gradle.dependencymanagement.DependencyManagement.resolveIfNecessary(DependencyManagement.groovy:134)
```

The build file:

```groovy
buildscript {
	ext {
		springBootVersion = '1.3.3.RELEASE'
	}
	repositories {
                mavenLocal()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}") 
	}
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'spring-boot' 

jar {
	baseName = 'foo'
	version = '0.0.1-SNAPSHOT'
}
sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenLocal()
}


dependencies {
	compile('org.springframework.cloud:spring-cloud-starter-eureka-server')
	testCompile('org.springframework.boot:spring-boot-starter-test') 
}

dependencyManagement {
	imports { 
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:Brixton.RC2" 
	}
}


eclipse {
	classpath {
		 containers.remove('org.eclipse.jdt.launching.JRE_CONTAINER')
		 containers 'org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8'
	}
}

task wrapper(type: Wrapper) {
	gradleVersion = '2.12'
}
```

Is this even possible?

**Comment by wilkinsona** [comment]
Yes, it should be possible. The error is rather misleading, and is something that I should improve in the plugin. What's happening is that the plugin is attempting to resolve a configuration and it's failed due to a missing dependency. This gets it into an unexpected state and ultimately causes it to try and modify the configuration that has already been unsuccessfully resolved. The plugin needs to catch the resolution failure, report the problem and fail the build rather than limping along and then failing later on.

If you run the `dependencies` task rather than `build`, you should get some better information about what's missing from your local Maven repository. For example:

```
$ ./gradlew build
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Cannot change dependencies of configuration 'detachedConfiguration1' after it has been resolved.

$ ./gradlew dependencies
:dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

archives - Configuration for archive artifacts.
:dependencies FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dependencies'.
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > Could not find org.springframework.cloud:spring-cloud-dependencies:Brixton.RC2.
     Searched in the following locations:
         file:/Users/awilkinson/.m2/repository/org/springframework/cloud/spring-cloud-dependencies/Brixton.RC2/spring-cloud-dependencies-Brixton.RC2.pom
         file:/Users/awilkinson/.m2/repository/org/springframework/cloud/spring-cloud-dependencies/Brixton.RC2/spring-cloud-dependencies-Brixton.RC2.pom
     Required by:
         :foo:unspecified
```

**Comment by wilkinsona** [comment]
I've improved the diagnostics in ed488e8. `build` will now provide information about the failure to resolve the imported boms:

```
./gradlew build
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration 'detachedConfiguration2'.
> Could not resolve org.springframework.cloud:spring-cloud-starter-eureka-server:.
  Required by:
      :foo:unspecified
   > Could not resolve imported Maven boms. Could not find org.springframework.cloud:spring-cloud-dependencies:Brixton.RC2.
     Searched in the following locations:
         file:/Users/awilkinson/.m2/repository/org/springframework/cloud/spring-cloud-dependencies/Brixton.RC2/spring-cloud-dependencies-Brixton.RC2.pom
         file:/Users/awilkinson/.m2/repository/org/springframework/cloud/spring-cloud-dependencies/Brixton.RC2/spring-cloud-dependencies-Brixton.RC2.pom
     Required by:
         :foo:unspecified
```

**Comment by kpb** [comment]
Thank you so much for the quick resolution and debugging tips - solved my (painful) issue.
